/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UlForm: typeof import('udesign-vue')['UlForm']
    UlMenu: typeof import('udesign-vue')['UlMenu']
    UlTable: typeof import('udesign-vue')['UlTable']
  }
}
